### ISSUE TITLE
navigation exception

### ISSUE THREAD

**Issue by yousefmohamed35** [heshamerfan97/flutter_quran#1]
![Screenshot (157)](https://github.com/user-attachments/assets/721580b8-2a09-48a6-85fe-242b3a6b6582)
when i click to navigate to surah the error in the photo is thrown 

{
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 171 pos 12: '_positions.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
}

thanks for your efforts

**Comment by heshamerfan97** [comment]
Are you calling `navigateToSurah()` from the same screen where you display Quran or not?
As `navigateToSurah()` communicate with **scrollController** attached to **Quran screens**, so if the Quran screen is disposed the **scrollController** will be attached to nothing.

**Comment by yousefmohamed35** [comment]
Yes I call it from the screen I displayed all Quran 
How I can use it

**Comment by heshamerfan97** [comment]
You can see the customized example [onTap function in SearchScreen](https://github.com/heshamerfan97/flutter_quran/blob/master/example/lib/customized_example/search_screen.dart#L51) as it will help you with your scenario.
Also an update is now published to avoid mis-usage while navigating through Quran, try upgrading to v0.0.2
